# Generated by Django 3.2.5 on 2022-04-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='물품ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('price', models.CharField(max_length=20, verbose_name='가격')),
                ('category', models.CharField(max_length=30, verbose_name='카테고리')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('image', models.CharField(default=None, max_length=300, verbose_name='상품이미지')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록일자')),
                ('delivery', models.CharField(default='무료배송', max_length=30, verbose_name='배송비')),
                ('seller', models.CharField(max_length=30, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'db_table': 'product',
            },
        ),
    ]
