# Generated by Django 3.2.5 on 2022-04-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEMBER', '0001_initial'),
        ('PRODUCT', '0001_initial'),
        ('ORDER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('rating', models.FloatField(verbose_name='별점')),
                ('detail', models.TextField(blank=True, verbose_name='상세리뷰')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEMBER.member')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORDER.order_items')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.product')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
                'db_table': 'review',
            },
        ),
    ]
