# Generated by Django 3.2.5 on 2022-04-08 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('category', models.CharField(max_length=30, verbose_name='카테고리')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('delivery', models.CharField(max_length=30, verbose_name='배송비')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='판매자이름')),
            ],
            options={
                'verbose_name': '판매자',
                'verbose_name_plural': '판매자들',
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='Product_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_file', models.FileField(upload_to='', verbose_name='원본파일')),
                ('add_file', models.FileField(upload_to='', verbose_name='변경파일')),
                ('thumbnail', models.FileField(upload_to='', verbose_name='썸네일')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': '제품사진',
                'verbose_name_plural': '제품사진들',
                'db_table': 'product_img',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.seller'),
        ),
    ]
