# Generated by Django 3.2.5 on 2022-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='네이버', max_length=30, verbose_name='판매자'),
        ),
    ]
