# Generated by Django 3.2.5 on 2022-04-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=None, max_length=300, verbose_name='상품이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.CharField(default='무료배송', max_length=30, verbose_name='배송비'),
        ),
        migrations.DeleteModel(
            name='Product_img',
        ),
    ]
