# Generated by Django 3.2.5 on 2022-04-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='product_img',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.IntegerField(default=0, verbose_name='물품ID'),
        ),
    ]
