# Generated by Django 3.2.5 on 2022-04-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220411_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False, verbose_name='물품ID'),
        ),
    ]
