# Generated by Django 3.2.5 on 2022-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=30, verbose_name='판매자'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
