# Generated by Django 3.2.5 on 2022-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220411_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일자'),
        ),
    ]
