# Generated by Django 3.2.5 on 2022-04-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MEMBER', '0001_initial'),
        ('PRODUCT', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=30, verbose_name='사유')),
                ('comment', models.TextField(default='', verbose_name='덧글')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MEMBER.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.product')),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜들',
                'db_table': 'pick',
            },
        ),
    ]
