# Generated by Django 3.2.5 on 2022-04-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='회원ID')),
                ('username', models.CharField(max_length=30, verbose_name='아이디')),
                ('pw', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('gender', models.CharField(max_length=2, verbose_name='성별')),
                ('email', models.EmailField(max_length=30, verbose_name='이메일')),
                ('phoneNum', models.IntegerField(max_length=11, verbose_name='폰번호')),
                ('birth', models.DateField(verbose_name='생년월일')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_num', models.IntegerField(verbose_name='우편번호')),
                ('address', models.CharField(max_length=70, verbose_name='주소')),
                ('address_detail', models.CharField(max_length=100, verbose_name='상세주소')),
                ('type', models.IntegerField(verbose_name='타입')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소들',
                'db_table': 'address',
            },
        ),
    ]
