# Generated by Django 3.2.5 on 2022-04-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_recent_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='recent_search',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='회원ID'),
        ),
    ]
