# Generated by Django 3.2.5 on 2022-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='선물수량'),
        ),
    ]
