# Generated by Django 3.2.5 on 2022-04-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='order_items_id',
            new_name='order_items',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
    ]
