# Generated by Django 3.2.5 on 2022-04-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='아이디')),
                ('pw', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('gender', models.CharField(max_length=2, verbose_name='성별')),
                ('email', models.CharField(max_length=30, verbose_name='이메일')),
                ('phoneNum', models.CharField(max_length=30, verbose_name='폰번호')),
                ('birth', models.DateField(verbose_name='생년월일')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
            ],
            options={
                'verbose_name': '상품별 주문',
                'verbose_name_plural': '상품별 주문들',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('category', models.CharField(max_length=30, verbose_name='카테고리')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('delivery', models.CharField(max_length=30, verbose_name='배송비')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='판매자이름')),
            ],
            options={
                'verbose_name': '판매자',
                'verbose_name_plural': '판매자들',
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='받는이 이름')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('file', models.FileField(upload_to='', verbose_name='첨부파일')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('phone', models.CharField(max_length=30, verbose_name='폰번호')),
                ('email', models.CharField(max_length=30, verbose_name='이메일')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
            ],
            options={
                'verbose_name': '고객센터',
                'verbose_name_plural': '고객센터들',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('rating', models.FloatField(verbose_name='평점')),
                ('detail', models.TextField(blank=True, verbose_name='상세리뷰')),
                ('view_cnt', models.IntegerField(default=0, verbose_name='조회수')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
                ('order_items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.order_items')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Recent_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=30, unique=True, verbose_name='단어')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='일자')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product')),
            ],
            options={
                'verbose_name': '최근검색기록',
                'verbose_name_plural': '최근검색기록들',
                'db_table': 'recent_search',
            },
        ),
        migrations.CreateModel(
            name='Product_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_file', models.FileField(upload_to='', verbose_name='원본파일')),
                ('add_file', models.FileField(upload_to='', verbose_name='변경파일')),
                ('thumbnail', models.FileField(upload_to='', verbose_name='썸네일')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product')),
            ],
            options={
                'verbose_name': '제품사진',
                'verbose_name_plural': '제품사진들',
                'db_table': 'product_img',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.seller'),
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=30, verbose_name='받는이 이름')),
                ('receiver_phone', models.CharField(max_length=30, verbose_name='받는이 휴대폰번호')),
                ('message', models.TextField(blank=True, verbose_name='메세지')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product')),
            ],
            options={
                'verbose_name': '선물',
                'verbose_name_plural': '선물들',
                'db_table': 'present',
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30, verbose_name='사유')),
                ('comment', models.TextField(blank=True, verbose_name='덧글')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product')),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜들',
                'db_table': 'pick',
            },
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='주문날짜')),
                ('delivery_address', models.CharField(max_length=30, verbose_name='배송지')),
                ('receiver_name', models.CharField(max_length=30, verbose_name='수령인')),
                ('receiver_phone', models.CharField(max_length=30, verbose_name='수령자전화번호')),
                ('eta', models.DateField(verbose_name='수령예상일')),
                ('number', models.IntegerField(verbose_name='주문번호')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문들',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.product')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니들',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_num', models.IntegerField(verbose_name='우편번호')),
                ('address', models.CharField(max_length=70, verbose_name='주소')),
                ('address_detail', models.CharField(max_length=100, verbose_name='상세주소')),
                ('type', models.IntegerField(verbose_name='타입')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duwon.member')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소들',
                'db_table': 'address',
            },
        ),
    ]
