# Generated by Django 3.2.5 on 2022-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='comment',
            field=models.TextField(default='', verbose_name='덧글'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='reason',
            field=models.CharField(default='', max_length=30, verbose_name='사유'),
        ),
    ]
