# Generated by Django 3.2.5 on 2022-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick', '0004_alter_pick_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='comment',
            field=models.TextField(blank=True, verbose_name='덧글'),
        ),
    ]
