# Generated by Django 3.2.5 on 2022-04-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='order_items',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='order_items',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='주문일련번호'),
        ),
    ]
