# Generated by Django 3.2.5 on 2022-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail_address',
            field=models.CharField(default='', max_length=60, verbose_name='상세배송지'),
        ),
    ]
