# Generated by Django 3.2.5 on 2022-04-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='detail_address',
            field=models.CharField(default='', max_length=60, verbose_name='상세배송지'),
        ),
        migrations.AddField(
            model_name='order',
            name='select_list',
            field=models.CharField(default='', max_length=30, verbose_name='배송시요구사항'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
    ]
