# Generated by Django 3.2.5 on 2022-04-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=60, verbose_name='배송지'),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail_address',
            field=models.CharField(default='', max_length=100, verbose_name='상세배송지'),
        ),
        migrations.AlterField(
            model_name='order',
            name='select_list',
            field=models.CharField(default='', max_length=50, verbose_name='배송시요구사항'),
        ),
    ]
