# Generated by Django 3.2.5 on 2022-04-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_temporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='eta',
        ),
    ]
