# Generated by Django 3.2.5 on 2022-04-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_detail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='select_list',
            field=models.CharField(default='', max_length=30, verbose_name='배송시요구사항'),
        ),
    ]
